const images = {
 cat: require('../assets/cat.png'),
 dog: require('../assets/dog.png'),
 polarBear: require('../assets/polar-bear.png'),
 unicorn: require('../assets/unicorn.png'),
 bird: require('../assets/bird.png'),
 beaver: require('../assets/beaver.png'),
 buffalo: require('../assets/buffalo.png'),
 chick: require('../assets/chick.png'),
 fish: require('../assets/fish.png'),
 dolphin: require('../assets/dolphin.png'),
 flamingo: require('../assets/flamingo.png'),
 frog: require('../assets/frog.png'),
 horse: require('../assets/horse.png'),
 lion: require('../assets/lion.png'),
 lizard: require('../assets/lizard.png'),
 lobster: require('../assets/lobster.png'),
 owl: require('../assets/owl.png'),
 panda: require('../assets/panda.png'),
 parrot: require('../assets/parrot.png'),
 raccoon: require('../assets/raccoon.png'),
 shark: require('../assets/shark.png'),
 sheep: require('../assets/sheep.png'),
 snake: require('../assets/snake.png'),
 tiger: require('../assets/tiger.png'),
 tropicalFish: require('../assets/tropical-fish.png'),
 turtle: require('../assets/turtle.png'),
 bear: require('../assets/bear.png'),
 tRex: require('../assets/t-rex.png'),
 rabbit: require('../assets/rabbit.png'),
 zebra: require('../assets/zebra.png'), 
}

const AnimalsData = {
  "Abel": `${images.cat}`,
  "Yasiris": `${images.dog}`,
  "Malee": `${images.panda}`,
  "Fatima": `${images.unicorn}`,
  "Jenia": `${images.owl}`,
  "Orlando": `${images.horse}`,
  "Luki": `${images.raccoon}`,
  "Dayron": `${images.bird}`,
  "Josue": `${images.fish}`,
  "Nathaly": `${images.tropicalFish}`,
  "Issac": `${images.lobster}`,
  "Julie": `${images.dolphin}`,
  "Daniel": `${images.lion}`,
  "Jonathan": `${images.tiger}`,
  "Oscar": `${images.polarBear}`,
  "Michelle": `${images.chick}`,
  "Tello": `${images.beaver}`,
  "Sterben": `${images.bear}`,
  "Elias": `${images.tRex}`,
  "Pride": `${images.sheep}`,
  "Miguel": `${images.buffalo}`,
  "Marjorie": `${images.shark}`,
  "Bryan": `${images.lizard}`,
  "Rene": `${images.frog}`,
  "Oliver": `${images.snake}`,
  "Ricki": `${images.parrot}`,
  "Ruth": `${images.flamingo}`,
  "Carlos": `${images.zebra}`,
  "Alexis": `${images.rabbit}`,
}

export default AnimalsData